//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4.SQL__ADO.Net__EF_
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusHistory
    {
        public int Id { get; set; }
        public int StatusId { get; set; }
        public int ContractId { get; set; }
        public System.DateTime DateCreate { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual Status Status { get; set; }
    }
}
